prefix: '[TransportPipes] '
pipename:
  pipe: 'Pipe'
  golden_pipe: '&6Golden-Pipe'
  iron_pipe: '&7Iron-Pipe'
  wrench: '&cWrench'
goldpipeinv:
  nameinv: '&rGolden Pipe'
  colors:
    white: 'White'
    yellow: '&eYellow'
    green: '&aGreen'
    blue: '&9Blue'
    red: '&cRed'
    black: '&0Black'
settingsinv:
  nameinv: '&rPlayer Settings'
  decrease: '&6Decrease'
  increase: '&6Increase'
  viewDistanceName: '&6View Distance: '
  viewDistanceLores:
  - '&7This represents the Radius in Blocks'
  - '&7in which you can see the pipes.'
  - '&7If you have too less FPS, decrease this option.'